version: '3'

services:
  web:
    build: .
    image: mcantillana/pycon:latest
    
    command: python manage.py runserver 0:8000
    env_file: 
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - net-pycon

volumes:
  db_data: 

networks:
  net-pycon:

